  notification:
      email: false

  language:
    python
  
  python:
    - "3.6"

  install:
    - pip install -r requirements.txt
    - pip install pytest-cov

  env: 
    - APP_SETTINGS='testing'
    - DATABASE_URL="dbname='qtest' host='127.0.0.1' port='5432' user='questioner' password='andela1'"
  
  services:
    - postgresql

  addons:
    postgresql: "9.6"

  before_script:
    - psql -c "CREATE USER questioner WITH PASSWORD 'andela1';" -U postgres 
    - psql -c 'CREATE DATABASE qtest;' -U postgres 
    - psql -c "GRANT ALL privileges on database qtest to questioner;" -U postgres 

  script:
    - py.test  --cov-report term --cov=app/api/

  after_success:
    - codecov