  notification:
      email: false

  language:
    python
  
  python:
    - "3.6"

  install:
    - pip install -r requirements.txt
    - pip install pytest-cov

  env: 
    - APP_SETTINGS='testing'
    - export DATABASE_URL="dbname='questioner' host='127.0.0.1' port='5432' user='questioner' password='andela1'"
  
  services:
    - postgresql

  addons:
    postgresql: "10.6"

  before_script:
    - sudo apt-get update
    - sudo apt-get install --yes postgresql-10
    - sudo apt-get install --yes postgresql-client-10
    - sudo /etc/init.d/postgresql restart
    - sleep 2
  
    - psql -c 'CREATE DATABASE questioner;' -U postgres
    - psql -c "CREATE USER questioner WITH PASSWORD 'andela1';" -U postgres
    - psql -c "GRANT ALL privileges on database questioner to questioner;" -U postgres

  script:
    - py.test  --cov-report term --cov=app/api/

  after_success:
    - codecov