DROP TABLE IF EXISTS usertbl CASCADE;
DROP TABLE IF EXISTS meetup CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS question CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS rsvp CASCADE;
DROP TABLE IF EXISTS voteup CASCADE;
DROP TABLE IF EXISTS votedown CASCADE;
